### ISSUE TITLE
QGIS rejects password for database and wont load layers

### ISSUE THREAD

**Issue by abeck58** [hauke96/qgis-outdoor-map#6]
![image](https://user-images.githubusercontent.com/38418219/146747515-c1e6da18-1d8a-46ca-b5c9-90dbbff3e77e.png)
![image](https://user-images.githubusercontent.com/38418219/146747372-df72113b-188a-4e7b-bb72-d7c66fa3bd06.png)

**Comment by hauke96** [comment]
Hi, thanks for checking out the project. I just tried the setup from scratch and everything worked for me. However I noticed that the README was a bit unclear about the database setup: At the end of the [docker setup section](https://github.com/hauke96/qgis-outdoor-map#start), the database is completely empty. When no data was imported to the database, I also get the dialog of unavailable layers but the login still works.

A few more details would be helpful:
* I see that you work on a Windows computer, do you still use docker for the database?
* If you use docker: Is everything running and working?
* If you don't use docker: Is postgres correctly configured and your installation working?
* Have you tried to login with a normal database client (PGAdmin or similar)?

**Comment by abeck58** [comment]
let me start by saying that while I am a tech guy development and coding go straight over my head. I'm doing the best I can and I am really keen to use your program, I have been looking for something like this for 2 years.

Ok typical troubleshooting the login issue fixed its self but I still get lots of unavailable layers.
![image](https://user-images.githubusercontent.com/38418219/146919607-c46a1bf9-7221-492a-9c4a-c23dc13a803c.png)

I have installed pgAdmin 4 but have never used it before, I've logged it but I have no idea if its working.
![image](https://user-images.githubusercontent.com/38418219/146919437-115382f8-ca61-4fa6-a61d-0dab27a5a6db.png)

**Comment by hauke96** [comment]
Ok the login works, that good. Have you imported the data into the database? When the database in empty, then of course all layers are missing/unavailable ;)

The process of filling the database is also described in the [README](https://github.com/hauke96/qgis-outdoor-map#fill-database). However, since you're working on Windows, the script `init.sh` will probably not work on a normal windows command line. The tool I use to import the data is `osm2pgsql` and is also [available on Windows](https://osm2pgsql.org/doc/). I think you still need the Windows terminal (PowerShell or similar) and them have to manually enter the command, whcih should be the same as I use on Linux: `osm2pgsql --create --slim -G --hstore --number-processes 4 "./your/file.pbf"`. More details can be found in the [manual](https://osm2pgsql.org/doc/manual.html#running-osm2pgsql) of `osm2pgsql`.

Please note that I'll probably will not support Windows or Mac here since I only use Linux. I simply wouldn't be able to fix bugs or add features to a Windows/Mac setup. But feel free to fork this project here on GitHub to manage your own adjustments/scripts/changes to this project.

**Comment by hauke96** [comment]
The current version of this project is not using Postgres anymore but GeoPackage files. I therefore close this issue.
